export const clients = [
    {
        id: 1,
        name: 'ABC Corporation',
        contactPerson: 'Alex Johnson',
        email: 'alex@abccorp.com',
        phone: '+1 234 567 8910',
        address: '123 Business Park, New York, NY 10001',
        industry: 'Technology',
        status: 'active',
        onboardingDate: '2023-01-15',
        notes: 'Key client for tax planning and audit services',
    },
    {
        id: 2,
        name: 'XYZ Limited',
        contactPerson: 'Sarah Thompson',
        email: 'sarah@xyzltd.com',
        phone: '+1 234 567 8911',
        address: '456 Corporate Avenue, Los Angeles, CA 90001',
        industry: 'Manufacturing',
        status: 'active',
        onboardingDate: '2023-02-20',
        notes: 'Quarterly compliance and GST filing',
    },
    {
        id: 3,
        name: 'Tech Innovators Inc',
        contactPerson: 'Michael Chen',
        email: 'michael@techinnovators.com',
        phone: '+1 234 567 8912',
        address: '789 Innovation Drive, San Francisco, CA 94105',
        industry: 'Technology',
        status: 'active',
        onboardingDate: '2023-03-10',
        notes: 'Startup requiring funding assistance and tax planning',
    },
    {
        id: 4,
        name: 'Global Traders Ltd',
        contactPerson: 'Priya Sharma',
        email: 'priya@globaltraders.com',
        phone: '+1 234 567 8913',
        address: '101 Trade Center, Chicago, IL 60601',
        industry: 'Import/Export',
        status: 'inactive',
        onboardingDate: '2022-11-05',
        notes: 'International tax compliance and customs advisory',
    },
    {
        id: 5,
        name: 'Hospitality Group',
        contactPerson: 'David Wilson',
        email: 'david@hospitalitygroup.com',
        phone: '+1 234 567 8914',
        address: '202 Hotel Plaza, Miami, FL 33101',
        industry: 'Hospitality',
        status: 'active',
        onboardingDate: '2023-04-18',
        notes: 'Multiple properties requiring consolidated financial statements',
    },
]; 